<?php /* @var $block \Divido\DividoFinancing\Block\Widget\BlockWidget */
if($block->showable()):
?>
<input
    type="<?php echo ($block->getData("showInput") == 1) ? "number" : "hidden"  ?>"
    id='dividoAmountInput'
    value="<?php echo $block->getData("defaultAmount"); ?>" 
    min="250" 
    max="25000" 
    placeholder="Enter amount "
    style="border-radius: 4px; padding: 4px; margin: 4px 0"
/>
<div id="dividoCalcWidget"
    data-divido-widget
    data-divido-title-logo
    data-divido-amount="<?php echo ($block->getData("defaultAmount")) ? $block->getData("defaultAmount") : 2000; ?>"
    data-divido-apply="true"
    data-divido-plans
    data-divido-logo 
    data-divido-mode
    >
</div>
                                        
<script>
document.getElementById('dividoAmountInput').addEventListener('keyup',function(event){
    let amount = event.target.value;
    let widget = document.getElementById('dividoCalcWidget');
    if(amount >= 250 && amount <= 25000){
        widget.setAttribute('data-divido-amount',amount);
        widget.style.display = "";
    }else{
        widget.style.display = "none";
    }
});
</script>
<?php endif; ?>